### ISSUE TITLE
AdminThemeUikit spacing issue

### ISSUE THREAD

**Issue by gmclelland** [adrianbj/ModuleSettingsImportExport#2]
Hi Adrian,

This is minor, but I noticed if I visit any module's settings page, I see the following when using AdminThemeUikit:
![modules processwire pwoliver test 2017-10-26 14-00-15](https://user-images.githubusercontent.com/40570/32071955-a00f86ac-ba56-11e7-8177-6987ab519a06.jpg)

**Comment by adrianbj** [comment]
Hi @gmclelland - this is a weird one. It has bugged me forever, but I don't think it is something my module should have to deal with. I think it should be something that the PW core takes care of.

Maybe it's a little unusual, but I nest a form inside a fieldset and that seems to be what messes things up, but unfortunately it seems to get messed up differently depending on the admin theme, so no one fix seems to work universally.

Any thoughts?

**Comment by gmclelland** [comment]
Hmm.. I'm not sure what the best way to fix this.  At first glance it seems like AdminThemeUikit should accommodate this.

**Comment by adrianbj** [comment]
Hey @gmclelland - I decided to fix this anyway - maybe it will be broken by future UiKit theme updates, but will deal with that if we ever need to.

**Comment by gmclelland** [comment]
Thanks Adrian!
