### ISSUE TITLE
Download and Remove Image?

### ISSUE THREAD

**Issue by eliasleyton** [adrianbj/ModuleSettingsImportExport#3]
I Try to upload a page with image field.

The module download the imagen and then deleted it? why?

<img width="445" alt="image" src="https://user-images.githubusercontent.com/3248095/71590654-2349e700-2b08-11ea-8e8a-9a73a0a9753a.png">

**Comment by adrianbj** [comment]
@eliasleyton - sorry I am confused - how is this module affecting images - this is only about module settings. Are you on the correct Github repo here?

**Comment by eliasleyton** [comment]
In this module, detect a possible bug, processwire clears the names of image files, and if this does not match the one configured in the JSON to import new pages, download it and then delete it.

My solution was to apply the same process to clean the file name and be able to achieve a later match.

**Comment by adrianbj** [comment]
Can you share which module you are using that stores a path to an image so I have something to test with?

**Comment by adrianbj** [comment]
@eliasleyton - it's been a while since I heard from you on this, so I am going to close now. If you want to provide more info, I can reopen and investigate further.
